version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: bee_seeker_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: beeseeker_backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: your_db_username
      DB_PASS: your_db_password
      DB_NAME: bee_seeker_db
      JWT_SECRET: your_jwt_secret
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: beeseeker_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
